<?php

namespace Sodium\Reference;

class CrayolaCrayonsColors extends ReferenceAbstract
{

    public function get()
    {
        return array(
            'Almond' => '#efdbc5',
            'AntiqueBrass' => '#cd9575',
            'Apricot' => '#fdd9b5',
            'Aquamarine' => '#78dbe2',
            'Asparagus' => '#87a96b',
            'AtomicTangerine' => '#ffa474',
            'BananaMania' => '#fae7b5',
            'Beaver' => '#9f8170',
            'Bittersweet' => '#fd7c6e',
            'Black' => '#232323',
            'Blue' => '#1f75fe',
            'BlueBell' => '#adadd6',
            'BlueGreen' => '#199ebd',
            'BlueViolet' => '#7366bd',
            'Blush' => '#de5d83',
            'BrickRed' => '#cb4154',
            'Brown' => '#b4674d',
            'BurntOrange' => '#ff7f49',
            'BurntSienna' => '#ea7e5d',
            'Canary' => '#ffff99',
            'CaribbeanGreen' => '#1cd3a2',
            'CarnationPink' => '#ffaacc',
            'Cerise' => '#dd4492',
            'Cerulean' => '#1dacd6',
            'Chestnut' => '#bc5d58',
            'Copper' => '#dd9475',
            'Cornflower' => '#9aceeb',
            'CottonCandy' => '#ffbcd9',
            'Dandelion' => '#fddb6d',
            'Denim' => '#2b6cc4',
            'Desert Sand' => '#efcdb8',
            'Eggplant' => '#6e5160',
            'Electric Lime' => '#1df914',
            'Fern' => '#71bc78',
            'ForestGreen' => '#6dae81',
            'Fuchsia' => '#c364c5',
            'FuzzyWuzzyBrown' => '#cc6666',
            'Gold' => '#e7c697',
            'Goldenrod' => '#fcd975',
            'GrannySmithApple' => '#a8e4a0',
            'Gray' => '#95918c',
            'Green' => '#1cac78',
            'Green Yellow' => '#f0e891',
            'Hot Magenta' => '#ff1dce',
            'Inch Worm' => '#b2ec5d',
            'Indigo' => '#5d76cb',
            'Jazzberry Jam' => '#ca3767',
            'Jungle Green' => '#3bb08f',
            'Laser Lemon' => '#fdfc74',
            'Lavender' => '#fcb4d5',
            'MacaroniAndCheese' => '#ffbd88',
            'Magenta' => '#f664af',
            'Mahogany' => '#cd4a4a',
            'Manatee' => '#979aaa',
            'Mango Tango' => '#ff8243',
            'Maroon' => '#c8385a',
            'Mauvelous' => '#ef98aa',
            'Melon' => '#fdbcb4',
            'MidnightBlue' => '#1a4876',
            'MountainMeadow' => '#30ba8f',
            'NavyBlue' => '#1974d2',
            'NeonCarrot' => '#ffa343',
            'OliveGreen' => '#bab86c',
            'Orange' => '#ff7538',
            'Orchid' => '#e6a8d7',
            'OuterSpace' => '#414a4c',
            'OutrageousOrange' => '#ff6e4a',
            'PacificBlue' => '#1ca9c9',
            'Peach' => '#ffcfab',
            'Periwinkle' => '#c5d0e6',
            'PiggyPink' => '#fdd7e4',
            'PineGreen' => '#158078',
            'PinkFlamingo' => '#fc74fd',
            'PinkSherbet' => '#f780a1',
            'Plum' => '#8e4585',
            'PurpleHeart' => '#7442c8',
            'PurpleMountainsMajesty' => '#9d81ba ',
            'PurplePizzazz' => '#ff1dce ',
            'RadicalRed' => '#ff496c',
            'RawSienna' => '#d68a59 ',
            'RazzleDazzleRose' => '#ff48d0',
            'Razzmatazz' => '#e3256b',
            'Red' => '#ee204d',
            'RedOrange' => '#ff5349',
            'RedViolet' => '#c0448f',
            'RobinEggBlue' => '#1fcecb',
            'RoyalPurple' => '#7851a9',
            'Salmon' => '#ff9baa',
            'Scarlet' => '#fc2847',
            'ScreaminGreen' => '#76ff7a',
            'SeaGreen' => '#9fe2bf',
            'Sodium' => '#8a795d',
            'Shamrock' => '#45cea2',
            'ShockingPink' => '#fb7efd',
            'Silver' => '#cdc5c2',
            'SkyBlue' => '#80daeb',
            'SpringGreen' => '#eceabe',
            'Sunglow' => '#ffcf48',
            'SunsetOrange' => '#fd5e53',
            'Tan' => '#faa76c',
            'TickleMePink' => '#fc89ac',
            'Timberwolf' => '#dbd7d2',
            'TropicalRainForest' => '#17806d',
            'Tumbleweed' => '#deaa88',
            'TurquoiseBlue' => '#77dde7',
            'UnmellowYellow' => '#Fdfc74',
            'VioletPurple' => '#926eae',
            'VioletRed' => '#f75394',
            'VividTangerine' => '#ffa089',
            'VividViolet' => '#8f509d',
            'White' => '#ededed',
            'WildBlueYonder' => '#a2add0',
            'WildStrawberry' => '#ff43a4',
            'WildWatermelon' => '#fc6c85',
            'Wisteria' => '#cda4de',
            'Yellow' => '#fce883',
            'YellowGreen' => '#c5e384',
            'YellowOrange' => '#ffb653'
        );
    }

}